version: '3.8'
services:
  mariadb:
    image: mariadb:11.0.2
    ports:
      - "3306:3306"
    volumes:
      - /home/master/nfs/kim5257-db-mariadb/data:/var/lib/mysql
    env_file:
      - ./db.env
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --event-scheduler=ON
      --max-connections=500
      --slow-query-log=ON
      --log-slow-query-time=1
    networks:
      - backbone
      - data
networks:
  backbone:
    name: kim5257_gateway_backbone
    external: true
  data:
